### ISSUE TITLE
UTC/JLT Issue

### ISSUE THREAD

**Issue by spioupiou** [spioupiou/is-kondo#13]
Thanks for the help Dillon and Mike!

@spioupiou Cédrine thanks for the work on this too! Played with it locally. I noticed that when I save a booking with "Today" (UI sets this to current date and time), the booked_date is saved as current date and time in Japan but the timezone is set to UTC.

Two ways we could resolve is to either: change the timezone to JPT or update the time to UTC. See `booked_date: Tue, 25 Jan 2022 12:05:00 UTC +00:00` below. Imo, its better to convert to UTC.

```ruby
[5] pry(main)> Booking.second
  Booking Load (0.5ms)  SELECT "bookings".* FROM "bookings" ORDER BY "bookings"."id" ASC LIMIT $1 OFFSET $2  [["LIMIT", 1], ["OFFSET", 1]]
=> #<Booking:0x00007fdf935746d8
 id: 7,
 user_id: 7,
 kondo_id: 40,
 confirmed: nil,
 booked_date: Tue, 25 Jan 2022 12:05:00 UTC +00:00,
 created_at: Tue, 25 Jan 2022 03:05:57 UTC +00:00,
 updated_at: Tue, 25 Jan 2022 03:05:57 UTC +00:00>
```

_Originally posted by @carlnoval in https://github.com/spioupiou/is-kondo/issues/12#issuecomment-1020766805_

**Comment by spioupiou** [comment]
Good point as well! I converted to UTC before making the booking as per below :) If there is a shorter way please let me know! (I struggled a little with that conversion!)

```
utc_date = date_params.to_s.to_time.utc
booked_date = DateTime.parse(utc_date.to_s)
@booking = Booking.new(user_id: current_user.id, kondo_id: params[:kondo_id], booked_date: booked_date)
```

![Screen Shot 2022-01-25 at 14 07 21](https://user-images.githubusercontent.com/68413600/150914849-9c1e700c-ce42-4e6a-89a4-5eaef6d99c5f.png)

**Comment by carlnoval** [comment]
I think this is good enough. 

The only other way I could think of is subtracting 9 hours from the booked date. 
```ruby
[20] pry(main)> Booking.second
  Booking Load (1.0ms)  SELECT "bookings".* FROM "bookings" ORDER BY "bookings"."id" ASC LIMIT $1 OFFSET $2  [["LIMIT", 1], ["OFFSET", 1]]
=> #<Booking:0x00007fdf93055440
 id: 7,
 user_id: 7,
 kondo_id: 40,
 confirmed: nil,
 booked_date: Tue, 25 Jan 2022 12:05:00 UTC +00:00,
 created_at: Tue, 25 Jan 2022 03:05:57 UTC +00:00,
 updated_at: Tue, 25 Jan 2022 03:05:57 UTC +00:00>
[21] pry(main)> a = Booking.second.booked_date
  Booking Load (4.3ms)  SELECT "bookings".* FROM "bookings" ORDER BY "bookings"."id" ASC LIMIT $1 OFFSET $2  [["LIMIT", 1], ["OFFSET", 1]]
=> Tue, 25 Jan 2022 12:05:00 UTC +00:00
[22] pry(main)> a - 9.hours
=> Tue, 25 Jan 2022 03:05:00 UTC +00:00
```
